apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: default
  labels:
    component: todo-api
spec:
  type: LoadBalancer
  selector:
    component: todo-api
  ports:
    - name: http
      port: 8000
      protocol: TCP